"""
Built-in Korean phonetic → English dictionary.

Maps Korean phonetic transliterations of English medical/academic terms
to their correct English forms. This works WITHOUT any API calls,
providing immediate correction even when screen analysis is unavailable.

Terms are organized by category. Each dict maps "한글음역" → "English".
Longer phrases are matched first to avoid partial replacement issues.
"""

ACADEMIC_TERMS = {
    "시스테매틱 리뷰": "systematic review",
    "메타 아날리시스": "meta-analysis",
    "메타아날리시스": "meta-analysis",
    "메타 분석": "meta-analysis",
    "랜덤마이즈드 컨트롤드 트라이얼": "randomized controlled trial",
    "랜더마이즈드 컨트롤드 트라이얼": "randomized controlled trial",
    "클리니컬 트라이얼": "clinical trial",
    "코호트 스터디": "cohort study",
    "케이스 컨트롤 스터디": "case-control study",
    "크로스 섹셔널 스터디": "cross-sectional study",
    "프로스펙티브 스터디": "prospective study",
    "레트로스펙티브 스터디": "retrospective study",
    "프로스펙티브": "prospective",
    "레트로스펙티브": "retrospective",
    "크로스 섹셔널": "cross-sectional",
    "랜덤마이즈드": "randomized",
    "랜더마이즈드": "randomized",
    "컨트롤드": "controlled",
    "코호트": "cohort",
    "트라이얼": "trial",
    "스터디": "study",
    "리서치": "research",
    "에비던스": "evidence",
    "에비던스 베이스드": "evidence-based",
    "가이드라인": "guideline",
    "프로토콜": "protocol",
    "컨센서스": "consensus",
    "레퍼런스": "reference",
    "리뷰": "review",
    "아티클": "article",
    "저널": "journal",
    "팔로우 업": "follow-up",
    "팔로우업": "follow-up",
    "아웃컴": "outcome",
    "엔드포인트": "endpoint",
    "엔드 포인트": "endpoint",
    "프라이머리 엔드포인트": "primary endpoint",
    "세컨더리 엔드포인트": "secondary endpoint",
    "서로게이트": "surrogate",
    "바이어스": "bias",
    "컨파운더": "confounder",
    "컨파운딩": "confounding",
    "셀렉션 바이어스": "selection bias",
    "리콜 바이어스": "recall bias",
    "샘플 사이즈": "sample size",
    "파워": "power",
    "인클루전 크라이티리아": "inclusion criteria",
    "익스클루전 크라이티리아": "exclusion criteria",
    "인폼드 컨센트": "informed consent",
    "피밸류": "p-value",
    "피 밸류": "p-value",
    "컨피던스 인터벌": "confidence interval",
    "오즈 레이시오": "odds ratio",
    "오즈레이시오": "odds ratio",
    "릴러티브 리스크": "relative risk",
    "앱솔루트 리스크": "absolute risk",
    "해저드 레이시오": "hazard ratio",
    "해저드레이시오": "hazard ratio",
    "인시던스": "incidence",
    "프리밸런스": "prevalence",
    "센시티비티": "sensitivity",
    "스페시피시티": "specificity",
    "포지티브 프리딕티브 밸류": "positive predictive value",
    "네거티브 프리딕티브 밸류": "negative predictive value",
    "프리딕티브 밸류": "predictive value",
    "시그니피컨트": "significant",
    "시그니피컨스": "significance",
    "스태티스티컬리 시그니피컨트": "statistically significant",
    "스태티스티컬": "statistical",
    "스탠다드 디비에이션": "standard deviation",
    "미디언": "median",
    "퍼센타일": "percentile",
    "코릴레이션": "correlation",
    "리그레션": "regression",
    "멀티베리어트": "multivariate",
    "유니베리어트": "univariate",
    "서브그룹 아날리시스": "subgroup analysis",
    "아날리시스": "analysis",
    "랜덤": "random",
    "스탠다드": "standard",
    "노멀": "normal",
    "프리젠테이션": "presentation",
    "데이터": "data",
    "데이타": "data",
    "샘플": "sample",
    "그룹": "group",
    "컨트롤": "control",
    "컨트롤 그룹": "control group",
    "리포트": "report",
    "케이스 리포트": "case report",
    "히스토리": "history",
    "피드백": "feedback",
    "스크리닝": "screening",
    "모니터링": "monitoring",
    "매니지먼트": "management",
    "어프로치": "approach",
    "스트래티지": "strategy",
    "메소드": "method",
    "테크닉": "technique",
    "프로세스": "process",
    "메커니즘": "mechanism",
    "팩터": "factor",
    "리스크 팩터": "risk factor",
    "리스크": "risk",
    "베네핏": "benefit",
    "임팩트": "impact",
    "이슈": "issue",
    "포커스": "focus",
    "클래시피케이션": "classification",
    "카테고리": "category",
    "크라이티리아": "criteria",
    "크라이테리아": "criteria",
    "인디케이션": "indication",
    "컨트라인디케이션": "contraindication",
    "스펙트럼": "spectrum",
}

CLINICAL_TERMS = {
    "다이어그노시스": "diagnosis",
    "디퍼렌셜 다이어그노시스": "differential diagnosis",
    "프로그노시스": "prognosis",
    "트리트먼트": "treatment",
    "테라피": "therapy",
    "프로필락시스": "prophylaxis",
    "컴플리케이션": "complication",
    "사이드 이펙트": "side effect",
    "어드벌스 이펙트": "adverse effect",
    "모탈리티": "mortality",
    "모비디티": "morbidity",
    "서바이벌": "survival",
    "서바이벌 레이트": "survival rate",
    "리미션": "remission",
    "컴플리트 리미션": "complete remission",
    "파셜 리미션": "partial remission",
    "릴랩스": "relapse",
    "리커런스": "recurrence",
    "엑서배이션": "exacerbation",
    "레미션": "remission",
    "사인": "sign",
    "심톰": "symptom",
    "심프톰": "symptom",
    "파인딩": "finding",
    "피지컬 이그잼": "physical exam",
    "피지컬": "physical",
    "익잼": "exam",
    "어세스먼트": "assessment",
    "애세스먼트": "assessment",
    "이밸류에이션": "evaluation",
    "워크업": "workup",
    "디퍼렌셜": "differential",
    "페이션트": "patient",
    "클리니컬": "clinical",
    "아큐트": "acute",
    "크로닉": "chronic",
    "서브아큐트": "subacute",
    "베나인": "benign",
    "말리그넌트": "malignant",
    "인베이시브": "invasive",
    "논인베이시브": "noninvasive",
    "시스테믹": "systemic",
    "로컬라이즈드": "localized",
    "퍼스트라인": "first-line",
    "퍼스트 라인": "first-line",
    "세컨드라인": "second-line",
    "세컨드 라인": "second-line",
    "서드라인": "third-line",
    "골드 스탠다드": "gold standard",
    "케모테라피": "chemotherapy",
    "라디에이션": "radiation",
    "라디에이션 테라피": "radiation therapy",
    "서제리": "surgery",
    "오퍼레이션": "operation",
    "트랜스플랜트": "transplant",
    "트랜스플랜테이션": "transplantation",
    "리섹션": "resection",
    "바이옵시": "biopsy",
    "이미징": "imaging",
    "시티 스캔": "CT scan",
    "시티스캔": "CT scan",
    "엠아라이": "MRI",
    "엑스레이": "X-ray",
    "울트라사운드": "ultrasound",
    "에코": "echo",
    "에코카디오그래피": "echocardiography",
    "엔도스코피": "endoscopy",
    "콜로노스코피": "colonoscopy",
    "브론코스코피": "bronchoscopy",
    "바이탈 사인": "vital signs",
    "블러드 프레셔": "blood pressure",
    "하트 레이트": "heart rate",
    "레스피레이토리 레이트": "respiratory rate",
    "사추레이션": "saturation",
    "옥시젠 사추레이션": "oxygen saturation",
    "랩": "lab",
    "랩 데이터": "lab data",
}

PHARMACOLOGY_TERMS = {
    "파마코키네틱스": "pharmacokinetics",
    "파마코다이나믹스": "pharmacodynamics",
    "파마콜로지": "pharmacology",
    "어고니스트": "agonist",
    "안타고니스트": "antagonist",
    "파셜 어고니스트": "partial agonist",
    "인히비터": "inhibitor",
    "블로커": "blocker",
    "액티베이터": "activator",
    "스티뮬레이터": "stimulator",
    "레셉터": "receptor",
    "리간드": "ligand",
    "바이오어베일러빌리티": "bioavailability",
    "하프라이프": "half-life",
    "하프 라이프": "half-life",
    "클리어런스": "clearance",
    "메타볼리즘": "metabolism",
    "도즈": "dose",
    "도즈 리스폰스": "dose-response",
    "로딩 도즈": "loading dose",
    "메인테넌스 도즈": "maintenance dose",
    "오버도즈": "overdose",
    "사이드이펙트": "side effect",
    "드러그 인터랙션": "drug interaction",
    "이펙트": "effect",
    "에피카시": "efficacy",
    "포텐시": "potency",
    "톡시시티": "toxicity",
    "컴플라이언스": "compliance",
    "어드히어런스": "adherence",
    "타겟": "target",
    "타겟 테라피": "targeted therapy",
    "앤티바이오틱": "antibiotic",
    "앤티바이러스": "antiviral",
    "앤티펀갈": "antifungal",
    "앤티코어귤런트": "anticoagulant",
    "앤티플레이틀릿": "antiplatelet",
    "앤티히스타민": "antihistamine",
    "앤티이메틱": "antiemetic",
    "앤티인플러메토리": "anti-inflammatory",
    "앤티파이레틱": "antipyretic",
    "아날제식": "analgesic",
    "엔세이드": "NSAID",
    "스테로이드": "steroid",
    "코르티코스테로이드": "corticosteroid",
    "이뮤노서프레선트": "immunosuppressant",
    "베타블로커": "beta blocker",
    "칼슘채널블로커": "calcium channel blocker",
    "에이스 인히비터": "ACE inhibitor",
    "에이알비": "ARB",
    "다이유레틱": "diuretic",
    "스타틴": "statin",
    "인슐린": "insulin",
    "오피오이드": "opioid",
    "벤조다이아제핀": "benzodiazepine",
    "바비튜레이트": "barbiturate",
}

PATHOLOGY_TERMS = {
    "패솔로지": "pathology",
    "패소피지올로지": "pathophysiology",
    "패토피지올로지": "pathophysiology",
    "페소피지올로지": "pathophysiology",
    "페토피지올로지": "pathophysiology",
    "에티올로지": "etiology",
    "피지올로지": "physiology",
    "인플러메이션": "inflammation",
    "인플레메이션": "inflammation",
    "피브로시스": "fibrosis",
    "네크로시스": "necrosis",
    "아폽토시스": "apoptosis",
    "프롤리퍼레이션": "proliferation",
    "디퍼렌시에이션": "differentiation",
    "뮤테이션": "mutation",
    "트렌스포메이션": "transformation",
    "매타스타시스": "metastasis",
    "메타스테이시스": "metastasis",
    "인베이전": "invasion",
    "앤지오제네시스": "angiogenesis",
    "하이퍼트로피": "hypertrophy",
    "하이퍼플레이지아": "hyperplasia",
    "에트로피": "atrophy",
    "어트로피": "atrophy",
    "디스플레이지아": "dysplasia",
    "메타플레이지아": "metaplasia",
    "네오플라즘": "neoplasm",
    "튜머": "tumor",
    "카시노마": "carcinoma",
    "사코마": "sarcoma",
    "림포마": "lymphoma",
    "류케미아": "leukemia",
    "마이엘로마": "myeloma",
    "이스케미아": "ischemia",
    "인팍션": "infarction",
    "쓰롬보시스": "thrombosis",
    "스롬보시스": "thrombosis",
    "엠볼리즘": "embolism",
    "헤머리지": "hemorrhage",
    "히모리지": "hemorrhage",
    "이디마": "edema",
    "에데마": "edema",
    "아테로스클레로시스": "atherosclerosis",
    "셉시스": "sepsis",
    "쇼크": "shock",
    "디아이씨": "DIC",
    "앱세스": "abscess",
    "그래뉼로마": "granuloma",
    "엑수데이트": "exudate",
    "트랜수데이트": "transudate",
}

BIOCHEMISTRY_TERMS = {
    "바이오케미스트리": "biochemistry",
    "몰레큘러": "molecular",
    "몰레큘러 바이올로지": "molecular biology",
    "셀룰러": "cellular",
    "시그널링": "signaling",
    "시그널링 패스웨이": "signaling pathway",
    "시그널 트랜스덕션": "signal transduction",
    "패스웨이": "pathway",
    "캐스케이드": "cascade",
    "트랜스크립션": "transcription",
    "트랜슬레이션": "translation",
    "레플리케이션": "replication",
    "익스프레션": "expression",
    "진 익스프레션": "gene expression",
    "프로테인": "protein",
    "엔자임": "enzyme",
    "서브스트레이트": "substrate",
    "코팩터": "cofactor",
    "코엔자임": "coenzyme",
    "키네이스": "kinase",
    "포스파타아제": "phosphatase",
    "포스포릴레이션": "phosphorylation",
    "디포스포릴레이션": "dephosphorylation",
    "유비퀴틴": "ubiquitin",
    "프로테아좀": "proteasome",
    "미토콘드리아": "mitochondria",
    "리보좀": "ribosome",
    "라이소좀": "lysosome",
    "골지": "Golgi",
    "엔도플라즈믹 레티큘럼": "endoplasmic reticulum",
    "글라이콜리시스": "glycolysis",
    "글루코네오제네시스": "gluconeogenesis",
    "베타 옥시데이션": "beta-oxidation",
    "옥시데이티브 포스포릴레이션": "oxidative phosphorylation",
    "에이티피": "ATP",
    "지티피": "GTP",
    "엔에이디에이치": "NADH",
    "디엔에이": "DNA",
    "알엔에이": "RNA",
    "메신저 알엔에이": "mRNA",
    "엠알엔에이": "mRNA",
    "피씨알": "PCR",
    "엘라이자": "ELISA",
    "웨스턴 블롯": "Western blot",
    "웨스턴블롯": "Western blot",
    "바이오마커": "biomarker",
    "제네틱": "genetic",
    "제노믹": "genomic",
    "에피제네틱": "epigenetic",
    "제노타입": "genotype",
    "피노타입": "phenotype",
    "폴리모피즘": "polymorphism",
    "에스엔피": "SNP",
}

IMMUNOLOGY_TERMS = {
    "이뮤놀로지": "immunology",
    "이뮤니티": "immunity",
    "인네이트 이뮤니티": "innate immunity",
    "어댑티브 이뮤니티": "adaptive immunity",
    "사이토카인": "cytokine",
    "케모카인": "chemokine",
    "인터루킨": "interleukin",
    "인터페론": "interferon",
    "티엔에프": "TNF",
    "히스타민": "histamine",
    "앤티바디": "antibody",
    "앤티젠": "antigen",
    "이뮤노글로불린": "immunoglobulin",
    "아이지지": "IgG",
    "아이지엠": "IgM",
    "아이지에이": "IgA",
    "아이지이": "IgE",
    "티 셀": "T cell",
    "비 셀": "B cell",
    "매크로파지": "macrophage",
    "덴드리틱 셀": "dendritic cell",
    "내추럴 킬러 셀": "natural killer cell",
    "엔케이 셀": "NK cell",
    "엠에이치씨": "MHC",
    "에이치엘에이": "HLA",
    "오토이뮨": "autoimmune",
    "하이퍼센시티비티": "hypersensitivity",
    "아나필락시스": "anaphylaxis",
    "그래프트": "graft",
    "그래프트 리젝션": "graft rejection",
    "백신": "vaccine",
    "백시네이션": "vaccination",
    "이뮤노서프레션": "immunosuppression",
    "톨 라이크 리셉터": "toll-like receptor",
    "티엘알": "TLR",
    "옵소나이제이션": "opsonization",
    "파고사이토시스": "phagocytosis",
    "컴플리먼트": "complement",
    "컴플리먼트 시스템": "complement system",
}

PHYSIOLOGY_TERMS = {
    "카디악 아웃풋": "cardiac output",
    "스트로크 볼륨": "stroke volume",
    "이젝션 프랙션": "ejection fraction",
    "프리로드": "preload",
    "애프터로드": "afterload",
    "컨트랙틸리티": "contractility",
    "블러드 프레셔": "blood pressure",
    "페리페럴 레지스턴스": "peripheral resistance",
    "벤틸레이션": "ventilation",
    "퍼퓨전": "perfusion",
    "가스 익스체인지": "gas exchange",
    "옥시젠": "oxygen",
    "카본 다이옥사이드": "carbon dioxide",
    "지에프알": "GFR",
    "크레아티닌": "creatinine",
    "일렉트로라이트": "electrolyte",
    "소디움": "sodium",
    "포타시움": "potassium",
    "칼슘": "calcium",
    "마그네슘": "magnesium",
    "오스몰랄리티": "osmolality",
    "에시드 베이스": "acid-base",
    "에시도시스": "acidosis",
    "알칼로시스": "alkalosis",
    "호메오스타시스": "homeostasis",
    "네거티브 피드백": "negative feedback",
    "포지티브 피드백": "positive feedback",
    "액션 포텐셜": "action potential",
    "디폴라리제이션": "depolarization",
    "리폴라리제이션": "repolarization",
    "시냅스": "synapse",
    "뉴로트랜스미터": "neurotransmitter",
}

ENDOCRINE_TERMS = {
    "호르몬": "hormone",
    "엔도크린": "endocrine",
    "코르티솔": "cortisol",
    "에피네프린": "epinephrine",
    "노르에피네프린": "norepinephrine",
    "도파민": "dopamine",
    "세로토닌": "serotonin",
    "아세틸콜린": "acetylcholine",
    "에스트로겐": "estrogen",
    "프로게스테론": "progesterone",
    "테스토스테론": "testosterone",
    "타이로이드": "thyroid",
    "타이록신": "thyroxine",
    "알도스테론": "aldosterone",
    "안지오텐신": "angiotensin",
    "레닌": "renin",
    "에이디에이치": "ADH",
    "옥시토신": "oxytocin",
    "프로스타글란딘": "prostaglandin",
    "에리스로포이에틴": "erythropoietin",
    "그로스 호르몬": "growth hormone",
    "그로스 팩터": "growth factor",
    "인슐린 라이크 그로스 팩터": "insulin-like growth factor",
    "아이지에프": "IGF",
    "글루카곤": "glucagon",
    "갈락토스": "galactose",
    "프럭토스": "fructose",
    "글루코스": "glucose",
    "파라토르몬": "parathyroid hormone",
    "파라타이로이드 호르몬": "parathyroid hormone",
    "피티에이치": "PTH",
    "칼시토닌": "calcitonin",
    "비타민디": "vitamin D",
    "비타민 디": "vitamin D",
    "칼시트리올": "calcitriol",
    "칼시디올": "calcidiol",
    "하이드록시 비타민디": "hydroxy vitamin D",
    "하이퍼칼세미아": "hypercalcemia",
    "하이포칼세미아": "hypocalcemia",
    "하이퍼파라타이로이디즘": "hyperparathyroidism",
    "하이포파라타이로이디즘": "hypoparathyroidism",
}

BONE_METABOLISM_TERMS = {
    "오스테오칼신": "osteocalcin",
    "오스테오클라스트": "osteoclast",
    "오스테오블라스트": "osteoblast",
    "오스테오사이트": "osteocyte",
    "오스테오포로시스": "osteoporosis",
    "오스테오피니아": "osteopenia",
    "오스테오말라시아": "osteomalacia",
    "시티엑스": "CTX",
    "씨티엑스": "CTX",
    "씨 터미널 텔로펩타이드": "C-terminal telopeptide",
    "엔티엑스": "NTX",
    "엔 터미널 텔로펩타이드": "N-terminal telopeptide",
    "피원엔피": "P1NP",
    "피 원 엔 피": "P1NP",
    "프로콜라겐": "procollagen",
    "알칼라인 포스파타아제": "alkaline phosphatase",
    "에이엘피": "ALP",
    "본 스페시픽 에이엘피": "bone-specific ALP",
    "비에스에이엘피": "BSALP",
    "디옥시피리디놀린": "deoxypyridinoline",
    "디피디": "DPD",
    "하이드록시프롤린": "hydroxyproline",
    "타르트레이트 레지스턴트 에시드 포스파타아제": "tartrate-resistant acid phosphatase",
    "트랩": "TRAP",
    "트랩 파이브비": "TRAP-5b",
    "본 미네랄 덴시티": "bone mineral density",
    "비엠디": "BMD",
    "덱사": "DEXA",
    "덱사 스캔": "DEXA scan",
    "듀얼 에너지 엑스레이": "dual-energy X-ray",
    "티 스코어": "T-score",
    "티스코어": "T-score",
    "제트 스코어": "Z-score",
    "프랙스": "FRAX",
    "프랙쳐": "fracture",
    "프랙처": "fracture",
    "컴프레션 프랙처": "compression fracture",
    "힙 프랙처": "hip fracture",
    "버티브럴 프랙처": "vertebral fracture",
    "버티브라": "vertebra",
    "비스포스포네이트": "bisphosphonate",
    "알렌드로네이트": "alendronate",
    "리세드로네이트": "risedronate",
    "졸레드로닉 애시드": "zoledronic acid",
    "졸레드로네이트": "zoledronate",
    "이반드로네이트": "ibandronate",
    "데노수맙": "denosumab",
    "프롤리아": "Prolia",
    "테리파라타이드": "teriparatide",
    "포르테오": "Forteo",
    "아바로파라타이드": "abaloparatide",
    "로모소주맙": "romosozumab",
    "이베니티": "Evenity",
    "라록시펜": "raloxifene",
    "바제독시펜": "bazedoxifene",
    "에스이알엠": "SERM",
    "셀렉티브 에스트로겐 리셉터 모듈레이터": "selective estrogen receptor modulator",
    "랭클": "RANKL",
    "랭크 리간드": "RANK ligand",
    "오피지": "OPG",
    "오스테오프로테게린": "osteoprotegerin",
    "스클레로스틴": "sclerostin",
    "본 턴오버": "bone turnover",
    "본 리모델링": "bone remodeling",
    "본 리솝션": "bone resorption",
    "본 포메이션": "bone formation",
    "리솝션": "resorption",
    "리모델링": "remodeling",
    "턴오버": "turnover",
    "본 마커": "bone marker",
    "본 턴오버 마커": "bone turnover marker",
    "콜라겐": "collagen",
    "타입 원 콜라겐": "type 1 collagen",
    "크로스링크": "crosslink",
    "트라베큘러 본": "trabecular bone",
    "코르티컬 본": "cortical bone",
    "피크 본 매스": "peak bone mass",
    "본 로스": "bone loss",
    "본 퀄리티": "bone quality",
    "마이크로아키텍처": "microarchitecture",
    "포스트메노포절": "postmenopausal",
    "메노포즈": "menopause",
    "글루코코르티코이드 인듀스드": "glucocorticoid-induced",
    "세컨더리 오스테오포로시스": "secondary osteoporosis",
    "프라이머리 오스테오포로시스": "primary osteoporosis",
    "드러그 홀리데이": "drug holiday",
}

OBGYN_TERMS = {
    "프리텀": "preterm",
    "프리 텀": "preterm",
    "딜리버리": "delivery",
    "프리텀 딜리버리": "preterm delivery",
    "프리텀 버스": "preterm birth",
    "프리텀 레이버": "preterm labor",
    "프리에클램프시아": "preeclampsia",
    "프리 에클램프시아": "preeclampsia",
    "에클램프시아": "eclampsia",
    "제스테이셔널": "gestational",
    "제스테이셔널 에이지": "gestational age",
    "제스테이셔널 다이어비티즈": "gestational diabetes",
    "시저리안": "cesarean",
    "시저리안 섹션": "cesarean section",
    "씨섹션": "C-section",
    "씨 섹션": "C-section",
    "인덕션": "induction",
    "오그멘테이션": "augmentation",
    "레이버": "labor",
    "세르비컬": "cervical",
    "세르빅스": "cervix",
    "다일레이션": "dilation",
    "이페이스먼트": "effacement",
    "트라이메스터": "trimester",
    "퍼스트 트라이메스터": "first trimester",
    "세컨드 트라이메스터": "second trimester",
    "서드 트라이메스터": "third trimester",
    "플라센타": "placenta",
    "플라센타 프리비아": "placenta previa",
    "플라센탈 어브럽션": "placental abruption",
    "앰니오틱": "amniotic",
    "앰니오틱 플루이드": "amniotic fluid",
    "앰니오센티시스": "amniocentesis",
    "프리머추어": "premature",
    "프리머처": "premature",
    "네오네이탈": "neonatal",
    "네오네이트": "neonate",
    "페리네이탈": "perinatal",
    "앤테네이탈": "antenatal",
    "프리네이탈": "prenatal",
    "포스트파텀": "postpartum",
    "포스트파텀 헤머리지": "postpartum hemorrhage",
    "엔도메트리움": "endometrium",
    "마이오메트리움": "myometrium",
    "유테러스": "uterus",
    "유테린": "uterine",
    "오바리": "ovary",
    "오바리안": "ovarian",
    "튜벌": "tubal",
    "엑토픽": "ectopic",
    "엑토픽 프레그넌시": "ectopic pregnancy",
    "프레그넌시": "pregnancy",
    "미스캐리지": "miscarriage",
    "어보션": "abortion",
    "스폰테이니어스 어보션": "spontaneous abortion",
    "페탈": "fetal",
    "페터스": "fetus",
    "피터스": "fetus",
    "엠브리오": "embryo",
    "임플란테이션": "implantation",
    "콘트랙션": "contraction",
    "싱글톤": "singleton",
    "트윈": "twin",
    "멀티플 제스테이션": "multiple gestation",
    "아프가 스코어": "Apgar score",
    "알디에스": "RDS",
    "레스피레이토리 디스트레스 신드롬": "respiratory distress syndrome",
    "엔아이씨유": "NICU",
    "비숍 스코어": "Bishop score",
    "브리치": "breech",
    "버텍스": "vertex",
    "에피지오토미": "episiotomy",
    "락테이션": "lactation",
    "브레스트피딩": "breastfeeding",
}

ANATOMY_TERMS = {
    "아나토미": "anatomy",
    "안테리어": "anterior",
    "포스테리어": "posterior",
    "레이터럴": "lateral",
    "미디얼": "medial",
    "수피리어": "superior",
    "인피리어": "inferior",
    "프록시멀": "proximal",
    "디스탈": "distal",
    "서피셜": "superficial",
    "딥": "deep",
    "빌래터럴": "bilateral",
    "유닐래터럴": "unilateral",
    "이프실래터럴": "ipsilateral",
    "컨트라래터럴": "contralateral",
    "루멘": "lumen",
    "스텐오시스": "stenosis",
    "오클루전": "occlusion",
    "다이세이션": "dilation",
    "퍼포레이션": "perforation",
}

LAB_TERMS = {
    "시비씨": "CBC",
    "씨비씨": "CBC",
    "비엠피": "BMP",
    "씨엠피": "CMP",
    "엘에프티": "LFT",
    "에이원씨": "A1C",
    "에이치비에이원씨": "HbA1c",
    "헤모글로빈": "hemoglobin",
    "헤마토크릿": "hematocrit",
    "플레이틀릿": "platelet",
    "알부민": "albumin",
    "빌리루빈": "bilirubin",
    "크레아티닌": "creatinine",
    "트로포닌": "troponin",
    "디다이머": "D-dimer",
    "비엔피": "BNP",
    "프로칼시토닌": "procalcitonin",
    "씨알피": "CRP",
    "이에스알": "ESR",
    "티에스에이치": "TSH",
    "프리 티포": "free T4",
    "에이엔에이": "ANA",
    "피티": "PT",
    "에이피티티": "aPTT",
    "아이엔알": "INR",
    "에이비지": "ABG",
    "유에이": "UA",
    "유린 아날리시스": "urinalysis",
    "콜레스테롤": "cholesterol",
    "엘디엘": "LDL",
    "에이치디엘": "HDL",
    "트리글리세라이드": "triglyceride",
}

CARDIOLOGY_TERMS = {
    "이씨지": "ECG",
    "이케이지": "EKG",
    "에이리얼 피브릴레이션": "atrial fibrillation",
    "에이피브": "AFib",
    "에이플러터": "atrial flutter",
    "브이택": "V-tach",
    "브이피브": "V-fib",
    "에스티 엘리베이션": "ST elevation",
    "스테미": "STEMI",
    "엔스테미": "NSTEMI",
    "에이씨에스": "ACS",
    "퍼큐테이니어스 코로나리 인터벤션": "percutaneous coronary intervention",
    "피씨아이": "PCI",
    "씨에이비지": "CABG",
    "스텐트": "stent",
    "밸브": "valve",
    "발브": "valve",
    "레귤지테이션": "regurgitation",
    "스테노시스": "stenosis",
    "머머": "murmur",
    "페리카디티스": "pericarditis",
    "마이오카디티스": "myocarditis",
    "엔도카디티스": "endocarditis",
    "카디오마이오패시": "cardiomyopathy",
    "아오틱": "aortic",
    "마이트럴": "mitral",
    "바이패스": "bypass",
}

PULMONOLOGY_TERMS = {
    "뉴모니아": "pneumonia",
    "뉴모소랙스": "pneumothorax",
    "에이알디에스": "ARDS",
    "씨오피디": "COPD",
    "애즈마": "asthma",
    "아스마": "asthma",
    "인튜베이션": "intubation",
    "익스튜베이션": "extubation",
    "벤틸레이터": "ventilator",
    "메카니컬 벤틸레이션": "mechanical ventilation",
    "피이이피": "PEEP",
    "타이달 볼륨": "tidal volume",
    "플루럴 이퓨전": "pleural effusion",
    "엠볼리즘": "embolism",
    "풀모너리 엠볼리즘": "pulmonary embolism",
    "피이": "PE",
    "디브이티": "DVT",
    "옥시젠 테라피": "oxygen therapy",
    "네뷸라이저": "nebulizer",
    "브론코다일레이터": "bronchodilator",
}


def get_builtin_korean_to_english() -> dict[str, str]:
    """Return all built-in Korean phonetic → English mappings combined."""
    combined = {}
    for d in [
        ACADEMIC_TERMS,
        CLINICAL_TERMS,
        PHARMACOLOGY_TERMS,
        PATHOLOGY_TERMS,
        BIOCHEMISTRY_TERMS,
        IMMUNOLOGY_TERMS,
        PHYSIOLOGY_TERMS,
        ENDOCRINE_TERMS,
        BONE_METABOLISM_TERMS,
        OBGYN_TERMS,
        ANATOMY_TERMS,
        LAB_TERMS,
        CARDIOLOGY_TERMS,
        PULMONOLOGY_TERMS,
    ]:
        combined.update(d)
    return combined
